### PR TITLE
[bndtools] updated sample service builder bundles

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
I am just going to pull this one ... :)

**Comment by AndyWu2015** [comment]
Hi Greg , I get build errors on my machine with your commit as following:
Cannot load the plugin com.liferay.ant.bnd.jsp.JspAnalyzerPlugin	bnd.bnd	/blade.servicebuilder.web	
Is it ok on your machine ?

**Comment by gamerson** [comment]
Hey Andy that was recently added by me to get the JSPAnalzerPlugin to run.
Can you try from command line and see if it builds?

On Thu, Sep 10, 2015 at 3:15 AM, Andy Wu <notifications@github.com> wrote:

> Hi Greg , I get build errors on my machine with your commit as following:
> Cannot load the plugin com.liferay.ant.bnd.jsp.JspAnalyzerPlugin bnd.bnd
> /blade.servicebuilder.web
>
> Is it ok on your machine ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/pull/135#issuecomment-139163474>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
Hi@gamerson, We are working with bndtools and it will build automatically . Is there any way to build from command line ?

**Comment by gamerson** [comment]
Yes just like gradle

$ gradle build



On Sun, Sep 13, 2015 at 9:58 PM, Andy Wu <notifications@github.com> wrote:

> Hi@gamerson, We are working with bndtools and it will build automatically
> . Is there any way to build from command line ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/pull/135#issuecomment-139947753>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
Hi Greg , I got the same errors when build in command line .

**Comment by gamerson** [comment]
We would need to enable the build on travis in order to see if this is
really a problem.

On Mon, Sep 14, 2015 at 7:59 PM, Andy Wu <notifications@github.com> wrote:

> Hi Greg , I got the same errors when build in command line .
>
> On Tue, Sep 15, 2015 at 3:19 AM, Gregory Amerson <notifications@github.com
> >
> wrote:
>
> > Yes just like gradle
> >
> > $ gradle build
> >
> >
> >
> > On Sun, Sep 13, 2015 at 9:58 PM, Andy Wu <notifications@github.com>
> wrote:
> >
> > > Hi@gamerson, We are working with bndtools and it will build
> > automatically
> > > . Is there any way to build from command line ?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/rotty3000/blade/pull/135#issuecomment-139947753>.
> > >
> >
> >
> >
> > --
> > Greg Amerson
> > Liferay Developer Tools
> > Liferay, Inc. www.liferay.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rotty3000/blade/pull/135#issuecomment-140181377>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/pull/135#issuecomment-140244079>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
I will try to enable the travis build today.

On Tue, Sep 15, 2015 at 3:01 PM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> We would need to enable the build on travis in order to see if this is
> really a problem.
>
> On Mon, Sep 14, 2015 at 7:59 PM, Andy Wu <notifications@github.com> wrote:
>
>> Hi Greg , I got the same errors when build in command line .
>>
>> On Tue, Sep 15, 2015 at 3:19 AM, Gregory Amerson <
>> notifications@github.com>
>> wrote:
>>
>> > Yes just like gradle
>> >
>> > $ gradle build
>> >
>> >
>> >
>> > On Sun, Sep 13, 2015 at 9:58 PM, Andy Wu <notifications@github.com>
>> wrote:
>> >
>> > > Hi@gamerson, We are working with bndtools and it will build
>> > automatically
>> > > . Is there any way to build from command line ?
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/rotty3000/blade/pull/135#issuecomment-139947753>.
>> > >
>> >
>> >
>> >
>> > --
>> > Greg Amerson
>> > Liferay Developer Tools
>> > Liferay, Inc. www.liferay.com
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/rotty3000/blade/pull/135#issuecomment-140181377>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rotty3000/blade/pull/135#issuecomment-140244079>.
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by AndyWu2015** [comment]
OK , Thanks

**Comment by AndyWu2015** [comment]
Hi Greg , I downloaded portal-service-7.0.0-SNAPSHOT jar file manually and
drop it into
${user.home}/.bnd/cache/aether-local/com/liferay/portal/portal-service/7.0.0-SNAPSHOT
folder , rerun "gradle build" and it built successfully ! So most of the
time it is network problem not bnd's problem .

**Pull request merged**
