### PR TITLE
[bndtools] rename to trackmen

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by AndyWu2015** [comment]
Hi greg , this project is for tracking Integration Points in Liferay OSGi runtime ?

**Comment by gamerson** [comment]
@AndyWu2015 exactly I was building it for research.  We don't necessarily need to port this to other tools, I just needed a place to put this where others could take a look.

**Comment by AndyWu2015** [comment]
Got it , So we can use this in our new module wizard to let user select a service to extend if they want to build a service type project , but we should let them start server first and if they change server we should detect it and let them run new server again .

**Comment by rotty3000** [comment]
Maybe there could be a light cache. The release could come with a
pre-analyzed list available from the "distro".

Then an option could be included to sync the list with the portal (to
account for new modules, and portal updates).

**Comment by gamerson** [comment]
yeah @rotty3000 I'm thinking we will do something like that, have a cached list internally to our tool but then if the user is up-and-running with a portal, we could try to run this in a remote bundle to grab this list again fresh.  which makes me wonder... would peter be interested in something like this in the ```bnd remote``` command either distro or a new command?

**Comment by rotty3000** [comment]
Not sure. We could ask!

**Pull request merged**
