### PR TITLE
Bladesampletest

### PR DESCRIPTION
**Pull request by lawrence-lee**
@gamerson Here are the updates.

### CODE REVIEW

**Comment by gamerson** [comment]
Hey Lawrence, did you see this?
https://travis-ci.org/rotty3000/blade/builds/114317665

On Mon, Mar 7, 2016 at 12:47 PM, Lawrence Lee <notifications@github.com>
wrote:

> Reopened #231 <https://github.com/rotty3000/blade/pull/231>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/pull/231#event-580580159>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by lawrence-lee** [comment]
@gamerson Yea, I'm not sure why it failed, but my guess is that at the root level, its not meant to do the gradle tasks at the individual project level.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/gamerson/blade/pull/6. [See changes here.](https://github.com/rotty3000/blade/compare/8b5a1a8~4...8b5a1a8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/rotty3000/blade/pull/235. [See changes here.](https://github.com/rotty3000/blade/compare/8b5a1a8~4...8b5a1a8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Pull request submitted to https://github.com/rotty3000/blade/pull/236. [See changes here.](https://github.com/rotty3000/blade/compare/807829e~5...807829e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
