### PR TITLE
Example overriding OSGi resource bundles

### PR DESCRIPTION
**Pull request by csierra**
This is an example on how to override the keys of portlets, taglibs or javascript and css from OSGi

### CODE REVIEW

**Comment by csierra** [comment]
yup... here you go!

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
hey @csierra  does this resource bundle example not need this in the bnd.bnd?
`-plugin.bundle: com.liferay.ant.bnd.resource.bundle.ResourceBundleLoaderAnalyzerPlugin`

**Comment by gamerson** [comment]
Closing this pull, it now lives here: https://github.com/gamerson/liferay-blade-samples/pull/8

**Comment by csierra** [comment]
hey @gamerson, 

aswering your question, it does not because what the plugin and the extender do is load and register the `ResourceBundleLoader`. In this example we are loading that _manually_ using 
```
new CacheResourceBundleLoader(
 			new ClassResourceBundleLoader(
 				"content.Language",
 				ResourceBundleLoaderComponent.class.getClassLoader())
```

**Pull request closed without merging**
