### PR TITLE
[gradle] update sb version to 1.0.54 and using "consume OSGi Services"

### PR DESCRIPTION
**Pull request by AndyWu2015**

### CODE REVIEW

**Comment by deadcyclo** [comment]
Something is wrong with this one. It doesn't compile. Missing import I'm guessing:

/tmp/dilldall/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/base/FooLocalServiceBaseImpl.java:37: error: package com.liferay.portal.kernel.module.framework.service does not exist
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
                                                         ^
/tmp/dilldall/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/base/FooLocalServiceBaseImpl.java:76: error: cannot find symbol
        implements FooLocalService, IdentifiableOSGiService {
                                    ^
  symbol: class IdentifiableOSGiService
/tmp/dilldall/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/base/FooServiceBaseImpl.java:28: error: package com.liferay.portal.kernel.module.framework.service does not exist
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
                                                         ^
/tmp/dilldall/blade/gradle/blade.servicebuilder.svc/src/main/java/blade/servicebuilder/service/base/FooServiceBaseImpl.java:52: error: cannot find symbol
        implements FooService, IdentifiableOSGiService {

**Comment by AndyWu2015** [comment]
Hi Brendan , update the portal-service-7.0.0-SNAPSHOT.jar dependency , and it will compile .

**Comment by deadcyclo** [comment]
Indeed. --refresh-dependencies did the trick :) Thanks Andy

**Comment by deadcyclo** [comment]
Hmm. I could not get this running on yesterdays nightly: 
Unresolved requirement: Import-Package: com.liferay.portal.kernel.module.framework.service; version="[7.0.0,8.
0.0)"_ [Sanitized]

Seems like todays nightly just got published, so I'll try it again once I've downloaded. I'm guessing that something changed between the two. An this is a non-issue. I'll let you know.

**Comment by deadcyclo** [comment]
Nope. Same issue with the latest nightly that was built a few hours ago :(

**Comment by deadcyclo** [comment]
Okey. So I guess I've found the issue here. This probably will run on a build from master, but not on the 7.x branch. Unfortunately seems there are no nightlies from master any more.

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by gamerson** [comment]
Merged, thanks! See b9b14e2...d4a462e <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by AndyWu2015** [comment]
You are right Brendan, It only works on master branch not 7.x branch . Thanks for reporting this .

**Pull request merged**
