### PR TITLE
IP - ConfigurationAction

### PR DESCRIPTION
**Pull request by kameshsampath**
Integration Point - Configuration Action with maven and gradle samples

### CODE REVIEW

**Comment by gamerson** [comment]
Is there an issue num we can close?

On Fri, Jun 12, 2015 at 12:20 AM, Kamesh Sampath <notifications@github.com>
wrote:

> Merged #99 <https://github.com/rotty3000/blade/pull/99>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/pull/99#event-328672511>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by kameshsampath** [comment]
Yes am going to update the corresponding isssue today, but then we still
have bndtools examples missing so wondering we need to close it or leave it
open.

**Comment by gamerson** [comment]
Good point, we should leave it open until we get bndtools working then.

On Fri, Jun 12, 2015 at 10:17 AM, Kamesh Sampath <notifications@github.com>
wrote:

> Yes am going to update the corresponding isssue today, but then we still
> have bndtools examples missing so wondering we need to close it or leave it
> open.
>
> On Fri 12 Jun, 2015 06:35 Gregory Amerson <notifications@github.com>
> wrote:
>
> > Is there an issue num we can close?
> >
> > On Fri, Jun 12, 2015 at 12:20 AM, Kamesh Sampath <
> notifications@github.com
> > >
> > wrote:
> >
> > > Merged #99 <https://github.com/rotty3000/blade/pull/99>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/rotty3000/blade/pull/99#event-328672511>.
> > >
> >
> >
> >
> > --
> > Greg Amerson
> > Liferay Developer Tools
> > Liferay, Inc. www.liferay.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rotty3000/blade/pull/99#issuecomment-111318498>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rotty3000/blade/pull/99#issuecomment-111329389>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by gamerson** [comment]
But just add a comment on that issue that maven adn gradle are in and only
need bndtools

Someone on my team will work on the bndtools soon and get it up2date.

On Fri, Jun 12, 2015 at 11:15 AM, Greg Amerson <gregory.amerson@liferay.com>
wrote:

> Good point, we should leave it open until we get bndtools working then.
>
> On Fri, Jun 12, 2015 at 10:17 AM, Kamesh Sampath <notifications@github.com
> > wrote:
>
>> Yes am going to update the corresponding isssue today, but then we still
>> have bndtools examples missing so wondering we need to close it or leave
>> it
>> open.
>>
>> On Fri 12 Jun, 2015 06:35 Gregory Amerson <notifications@github.com>
>> wrote:
>>
>> > Is there an issue num we can close?
>> >
>> > On Fri, Jun 12, 2015 at 12:20 AM, Kamesh Sampath <
>> notifications@github.com
>> > >
>> > wrote:
>> >
>> > > Merged #99 <https://github.com/rotty3000/blade/pull/99>.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/rotty3000/blade/pull/99#event-328672511>.
>> > >
>> >
>> >
>> >
>> > --
>> > Greg Amerson
>> > Liferay Developer Tools
>> > Liferay, Inc. www.liferay.com
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/rotty3000/blade/pull/99#issuecomment-111318498>.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rotty3000/blade/pull/99#issuecomment-111329389>.
>>
>
>
>
> --
> Greg Amerson
> Liferay Developer Tools
> Liferay, Inc. www.liferay.com
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Pull request merged**
