### PR TITLE
Master consolidate 2

### PR DESCRIPTION
**Pull request by lawrence-lee**
Rebasing from https://github.com/rotty3000/blade/pull/238

### CODE REVIEW

**Comment by gamerson** [comment]
We need to get travis build to not fail before we can merge.

**Comment by lawrence-lee** [comment]
Yep. Just pushed some changes.

**Comment by lawrence-lee** [comment]
woohoo! Passing! But yea I dont know if adding a shell script is the best solution for this repository. I dont know any other ways to call both gradle and maven.

**Comment by rotty3000** [comment]
Maybe I missed it (if I did just point me at the discussion so I can review) but why do we need the script?

**Comment by lawrence-lee** [comment]
Hah! maybe I should explain a bit more. But let's take this pull as the start of a discussion

We're trying to get the blade samples tested by the Jenkins cohort in the LA office instead of using Travis CI. The eventual goal would be to run integration tests so leveraging the Jenkins cohort would be our best use of resources. And instead of asking someone on the Jenkins infrastructure team to update Jenkins every time we want to add something, we would be able to control what tasks are being run from our repo. 

I hope this makes sense. I'm totally open to other solutions as well.

**Comment by rotty3000** [comment]
Couldn't we add the script without touching the travis file?

**Comment by rotty3000** [comment]
Better even would be to use https://wiki.jenkins-ci.org/display/JENKINS/Travis+YML+Plugin

**Comment by lawrence-lee** [comment]
We can add the script without touching the travis file. The plugin might be harder to add because they'd have to take down 2000+ servers to add a plugin to Jenkins.

**Comment by rotty3000** [comment]
Right, so leaving the travis file alone would be good at least until we see
significant benefit from jenkins.

We lose some travis features when using a script like this.

**Comment by lawrence-lee** [comment]
Okay. I'll close this PR and submit another one. Thanks Ray!

**Pull request closed without merging**
