### PR TITLE
Freemarker fix

### PR DESCRIPTION
**Pull request by deadcyclo**

### CODE REVIEW

**Comment by gamerson** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rotty3000** [comment]
This could be due to a regression. I'll have to take a look in the core and try to get this back working without having to make this change.

watch this space.

**Comment by deadcyclo** [comment]
@rotty3000 Most definitely something wrong here I think. I also discovered that the copy-request-parameters is also ignored when using thre FreemarkerPortlet. That was previously working fine.

**Comment by rotty3000** [comment]
this issue will be fixed in master of liferay-portal hopefully shortly, but I've applied the changes here to reflect how things should work.

Also, @deadcyclo I borrowed your idea to output something in the UI. I hope you don't mind it's mixed in with the other changes!

**Pull request closed without merging**
